import ObserverEquivariance.ProductModel
import Mathlib.GroupTheory.Perm.Cycle.Concrete

/-!
# A nontrivial twist: `C₃ ⋊ C₂ ≅ S₃` (paper `ex:twist`, instance of `thm:twisted`)

Paper labels covered:
* `ex:twist` — the base `S = Pair({0,1})`, `G = C₃`, the subgroup `H = C₂ = ⟨A⟩` generated by
  the interchange `A` of the two base objects, the twist `θ_A(g) = g⁻¹` (defined on `H`), the
  product presentation `O = S × Pair(C₃)`, the identification
  `Sym_H^θ(p) ≅ C₃ ⋊ C₂ ≅ S₃`, the conjugation formula `Ã_θ Λ_r Ã_θ⁻¹ = Λ_{r⁻¹}`, and the separate
  `S₃` illustration of left versus right translation;
* `thm:twisted` — used through `autBoxGθOverMulEquivSemidirect` and `liftHomθOver_conj` (Core).

The older `zmod3SemidirectWitness` of Core (the model `labData G3 G3` over `SingleObj G3`) is a
different model and is left untouched.

Conventions.
* Groups of strict automorphisms multiply in operator order: `(e₁ * e₂).hom = e₂.hom ⋙ e₁.hom`.
  Hence the paper's `Ã_θ Λ_r Ã_θ⁻¹` is the group product `Ã * Λ_r * Ã⁻¹`.
* Permutations: mathlib's `Equiv.Perm` multiplication is composition from right to left
  (`(σ * τ) i = σ (τ i)`), which is the paper's operator order.  The paper's one-based cycles on
  `{1,2,3}` correspond to zero-based cycles on `Fin 3`:
  `(12) ↦ swap 0 1`, `(23) ↦ swap 1 2`, `(123) ↦ c[0, 1, 2]`, `(132) ↦ c[0, 2, 1]`.
-/

open CategoryTheory

universe v

namespace TwistExample

/-! ## Local helpers: homomorphisms and isomorphisms between groups of order two -/

section C2

variable {A B : Type*} [Group A] [Group B]

/-- A homomorphism out of a group `A = {1, a}` of order at most two, sending `a` to an element
    `b` with `b * b = 1` (helper for paper `ex:twist`, where `H = C₂`). -/
def c2Hom [DecidableEq A] (a : A) (hA : ∀ x : A, x = 1 ∨ x = a) (ha : a ≠ 1) (haa : a * a = 1)
    (b : B) (hbb : b * b = 1) : A →* B where
  toFun x := if x = 1 then 1 else b
  map_one' := if_pos rfl
  map_mul' x y := by
    rcases hA x with rfl | rfl <;> rcases hA y with rfl | rfl <;> simp [ha, haa, hbb]

/-- `c2Hom` sends `1` to `1` (helper for paper `ex:twist`). -/
@[simp] theorem c2Hom_one' [DecidableEq A] (a : A) (hA : ∀ x : A, x = 1 ∨ x = a) (ha : a ≠ 1)
    (haa : a * a = 1) (b : B) (hbb : b * b = 1) : c2Hom a hA ha haa b hbb 1 = 1 :=
  if_pos rfl

/-- `c2Hom` sends the generator `a` to `b` (helper for paper `ex:twist`). -/
@[simp] theorem c2Hom_gen [DecidableEq A] (a : A) (hA : ∀ x : A, x = 1 ∨ x = a) (ha : a ≠ 1)
    (haa : a * a = 1) (b : B) (hbb : b * b = 1) : c2Hom a hA ha haa b hbb a = b :=
  if_neg ha

/-- Two groups `A = {1, a}`, `B = {1, b}` of order exactly two are isomorphic via `a ↦ b`
    (helper for paper `ex:twist`: `H ≅ C₂`). -/
def c2MulEquiv [DecidableEq A] [DecidableEq B] (a : A) (hA : ∀ x : A, x = 1 ∨ x = a)
    (ha : a ≠ 1) (haa : a * a = 1) (b : B) (hB : ∀ y : B, y = 1 ∨ y = b) (hb : b ≠ 1)
    (hbb : b * b = 1) : A ≃* B :=
  { c2Hom a hA ha haa b hbb with
    invFun := c2Hom b hB hb hbb a haa
    left_inv := fun x => by
      rcases hA x with rfl | rfl
      · simp only [OneHom.toFun_eq_coe, MonoidHom.toOneHom_coe, c2Hom_one']
      · simp only [OneHom.toFun_eq_coe, MonoidHom.toOneHom_coe, c2Hom_gen]
    right_inv := fun y => by
      rcases hB y with rfl | rfl
      · simp only [OneHom.toFun_eq_coe, MonoidHom.toOneHom_coe, c2Hom_one']
      · simp only [OneHom.toFun_eq_coe, MonoidHom.toOneHom_coe, c2Hom_gen] }

/-- `c2MulEquiv` sends the generator to the generator (helper for paper `ex:twist`). -/
@[simp] theorem c2MulEquiv_gen [DecidableEq A] [DecidableEq B] (a : A)
    (hA : ∀ x : A, x = 1 ∨ x = a) (ha : a ≠ 1) (haa : a * a = 1) (b : B)
    (hB : ∀ y : B, y = 1 ∨ y = b) (hb : b ≠ 1) (hbb : b * b = 1) :
    c2MulEquiv a hA ha haa b hB hb hbb a = b :=
  if_neg ha

end C2

/-! ## `C₂ = Multiplicative (ZMod 2)` and `C₃ = G3` -/

/-- The generator of `C₂ = Multiplicative (ZMod 2)` (paper `ex:twist`). -/
def c2Gen : Multiplicative (ZMod 2) := Multiplicative.ofAdd 1

/-- Every element of `C₂` is `1` or the generator (paper `ex:twist`). -/
theorem c2_cases : ∀ k : Multiplicative (ZMod 2), k = 1 ∨ k = c2Gen := by decide

/-- The generator of `C₂` is nontrivial (paper `ex:twist`). -/
theorem c2Gen_ne_one : c2Gen ≠ 1 := by decide

/-- The generator of `C₂` is an involution (paper `ex:twist`). -/
theorem c2Gen_mul_self : c2Gen * c2Gen = 1 := by decide

/-- Inversion on `C₃` is an involution of `G3` (paper `ex:twist`: `θ_A² = 1`). -/
theorem zmod3NegMulAut_mul_self : zmod3NegMulAut * zmod3NegMulAut = 1 := by
  ext g
  exact inv_inv g

end TwistExample

open TwistExample

/-! ## The base `S = Pair({0,1})` and the interchange `A` -/

/-- The base of paper `ex:twist`, `S = Pair({0,1})`, is connected (needed by `thm:twisted`). -/
theorem twistBase_isConnected : IsConnected (Pair (Fin 2)) := inferInstance

/-- The functor interchanging the two objects of `Pair({0,1})` (paper `ex:twist`, the base
    symmetry `A`). -/
def swapFunctor : Pair (Fin 2) ⥤ Pair (Fin 2) where
  obj x := ⟨Equiv.swap (0 : Fin 2) 1 x.pt⟩
  map _ := ⟨⟩

/-- The interchange is an involution on the nose (paper `ex:twist`).  The hom universe of
    `Pair` is pinned to a single `v` so that the intermediate universe is determined. -/
theorem swapFunctor_comp_self : swapFunctor.{v, v} ⋙ swapFunctor.{v, v} = 𝟭 (Pair (Fin 2)) :=
  CategoryTheory.Functor.ext (fun x => by cases x; simp [swapFunctor])
    (fun _ _ _ => Subsingleton.elim _ _)

/-- The interchange `A` of the two base objects as a strict automorphism of `Pair({0,1})`
    (paper `ex:twist`). -/
def swapAut : StrictAut (Pair (Fin 2)) :=
  ⟨swapFunctor, swapFunctor, swapFunctor_comp_self, swapFunctor_comp_self⟩

/-- `A² = 1` (paper `ex:twist`). -/
theorem swapAut_mul_self : swapAut * swapAut = 1 :=
  StrictAut.ext swapFunctor_comp_self swapFunctor_comp_self

/-- The interchange `A` sends the base object `0` to `1` (paper `ex:twist`: `A` interchanges
    the two base objects). -/
theorem swapAut_obj_zero : swapAut.hom.obj (⟨0⟩ : Pair (Fin 2)) = ⟨1⟩ := rfl

/-- The interchange `A` sends the base object `1` to `0` (paper `ex:twist`: `A` interchanges
    the two base objects). -/
theorem swapAut_obj_one : swapAut.hom.obj (⟨1⟩ : Pair (Fin 2)) = ⟨0⟩ := rfl

/-- Paper `ex:twist`: `A` interchanges the two base objects, `A 0 = 1` and `A 1 = 0`. -/
theorem swapAut_obj :
    swapAut.hom.obj (⟨0⟩ : Pair (Fin 2)) = ⟨1⟩ ∧ swapAut.hom.obj (⟨1⟩ : Pair (Fin 2)) = ⟨0⟩ :=
  ⟨rfl, rfl⟩

/-- `A ≠ 1`: it moves the object `0` to `1` (paper `ex:twist`). -/
theorem swapAut_ne_one : swapAut ≠ 1 := by
  intro h
  have h0 := congrArg (fun B : StrictAut (Pair (Fin 2)) => (B.hom.obj ⟨0⟩).pt) h
  exact absurd h0 (by decide)

/-- The subgroup `H = C₂ = ⟨A⟩ ≤ Aut(S)` generated by the interchange (paper `ex:twist`). -/
def twistH : Subgroup (StrictAut (Pair (Fin 2))) := Subgroup.zpowers swapAut

/-- The elements of `H = ⟨A⟩` are exactly `1` and `A` (paper `ex:twist`). -/
theorem mem_twistH {B : StrictAut (Pair (Fin 2))} : B ∈ twistH ↔ B = 1 ∨ B = swapAut := by
  constructor
  · intro hB
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.1 hB
    obtain ⟨m, rfl | rfl⟩ := Int.even_or_odd' k
    · left
      rw [zpow_mul, zpow_two, swapAut_mul_self, one_zpow]
    · right
      rw [zpow_add_one, zpow_mul, zpow_two, swapAut_mul_self, one_zpow, one_mul]
  · rintro (rfl | rfl)
    · exact one_mem _
    · exact Subgroup.mem_zpowers _

/-- The interchange `A` as an element of `H` (paper `ex:twist`). -/
def twistHSwap : twistH := ⟨swapAut, Subgroup.mem_zpowers _⟩

/-- Every element of `H` is `1` or `A` (paper `ex:twist`). -/
theorem twistH_cases (B : twistH) : B = 1 ∨ B = twistHSwap := by
  rcases mem_twistH.1 B.2 with h | h
  · exact Or.inl (Subtype.ext h)
  · exact Or.inr (Subtype.ext h)

/-- `A ≠ 1` in `H` (paper `ex:twist`). -/
theorem twistHSwap_ne_one : twistHSwap ≠ 1 := fun h => swapAut_ne_one (congrArg Subtype.val h)

/-- `A² = 1` in `H` (paper `ex:twist`). -/
theorem twistHSwap_mul_self : twistHSwap * twistHSwap = 1 := Subtype.ext swapAut_mul_self

open Classical in
/-- `H = ⟨A⟩ ≅ C₂ = Multiplicative (ZMod 2)`, `A ↦ ofAdd 1` (paper `ex:twist`). -/
noncomputable def twistHMulEquiv : twistH ≃* Multiplicative (ZMod 2) :=
  c2MulEquiv twistHSwap twistH_cases twistHSwap_ne_one twistHSwap_mul_self
    c2Gen c2_cases c2Gen_ne_one c2Gen_mul_self

/-- `twistHMulEquiv` sends `A` to the generator of `C₂` (paper `ex:twist`). -/
theorem twistHMulEquiv_swap : twistHMulEquiv twistHSwap = c2Gen := by
  classical
  exact c2MulEquiv_gen _ _ _ _ _ _ _ _

/-- `H` has order two (paper `ex:twist`: `H = C₂`). -/
theorem twistH_card : Nat.card twistH = 2 := by
  rw [Nat.card_congr twistHMulEquiv.toEquiv, Nat.card_eq_fintype_card]
  rfl

/-! ## The twist `θ : H →* Aut(C₃)`, `θ_A(g) = g⁻¹` -/

open Classical in
/-- The twist of paper `ex:twist`, defined on the subgroup `H`: `θ_1 = id`, `θ_A(g) = g⁻¹`. -/
noncomputable def twistθ : twistH →* MulAut G3 :=
  c2Hom twistHSwap twistH_cases twistHSwap_ne_one twistHSwap_mul_self
    zmod3NegMulAut zmod3NegMulAut_mul_self

/-- `θ_A` is inversion (paper `ex:twist`). -/
theorem twistθ_swap : twistθ twistHSwap = zmod3NegMulAut := by
  classical
  exact c2Hom_gen _ _ _ _ _ _

/-- `θ_A(g) = g⁻¹` (paper `ex:twist`). -/
theorem twistθ_swap_apply (g : G3) : twistθ twistHSwap g = g⁻¹ := by
  rw [twistθ_swap]; rfl

/-- The twist is nontrivial: `θ ≠ 1` (paper `ex:twist`). -/
theorem twistθ_ne_one : twistθ ≠ 1 := by
  intro h
  have h' := DFunLike.congr_fun h twistHSwap
  rw [twistθ_swap, MonoidHom.one_apply] at h'
  exact zmod3NegMulAut_ne_one h'

/-- The same twist on the abstract `C₂`: `ofAdd 1 ↦ inversion` (paper `ex:twist`, the
    `θ` of `C₃ ⋊ C₂`). -/
def twistθC2 : Multiplicative (ZMod 2) →* MulAut G3 :=
  c2Hom c2Gen c2_cases c2Gen_ne_one c2Gen_mul_self zmod3NegMulAut zmod3NegMulAut_mul_self

/-! ## The presentation and the semidirect classification -/

/-- The presentation of paper `ex:twist`: `O = S × Pair(C₃)` over `S = Pair({0,1})` with its
    normalized transport (the product model). -/
abbrev twistData : OEData G3 (CategoryTheory.Prod.fst (Pair (Fin 2)) (Pair G3)) :=
  productData (Pair (Fin 2)) G3

/-- Paper `ex:twist` via `thm:twisted`: `Sym_H^θ(p) ≅ C₃ ⋊_θ H`. -/
noncomputable def twistSemidirectH :
    AutBoxGθOver twistData twistH twistθ ≃* SemidirectProduct G3 twistH twistθ :=
  autBoxGθOverMulEquivSemidirect twistData twistH twistθ

/-- Transport of the twist along `H ≅ C₂` (paper `ex:twist`). -/
noncomputable def twistSemidirectC2 :
    SemidirectProduct G3 twistH twistθ ≃* SemidirectProduct G3 (Multiplicative (ZMod 2)) twistθC2 :=
  SemidirectProduct.congr (MulEquiv.refl G3) twistHMulEquiv (fun B => by
    rcases twistH_cases B with rfl | rfl
    · ext g
      simp [twistθC2]
    · ext g
      simp [twistHMulEquiv_swap, twistθ_swap, twistθC2, c2Gen])

/-- Paper `ex:twist`: `Sym_H^θ(p) ≅ C₃ ⋊ C₂` with `θ` the inversion. -/
noncomputable def twistSym :
    AutBoxGθOver twistData twistH twistθ
      ≃* SemidirectProduct G3 (Multiplicative (ZMod 2)) twistθC2 :=
  twistSemidirectH.trans twistSemidirectC2

/-! ## `C₃ ⋊ C₂ ≅ S₃` -/

/-- The three-cycle `(123) = (12)(23)` of `S₃`, i.e. `c[0, 1, 2]` on `Fin 3` (paper `ex:twist`). -/
def s3Rot : Equiv.Perm (Fin 3) := Equiv.swap 0 1 * Equiv.swap 1 2

/-- `C₃ →* S₃`, `ofAdd k ↦ (123)^k` (paper `ex:twist`). -/
def c3ToS3 : G3 →* Equiv.Perm (Fin 3) where
  toFun k := s3Rot ^ (Multiplicative.toAdd k).val
  map_one' := by decide
  map_mul' := by decide

/-- `C₂ →* S₃`, `ofAdd 1 ↦ (12)` (paper `ex:twist`). -/
def c2ToS3 : Multiplicative (ZMod 2) →* Equiv.Perm (Fin 3) :=
  c2Hom c2Gen c2_cases c2Gen_ne_one c2Gen_mul_self (Equiv.swap 0 1) (Equiv.swap_mul_self 0 1)

/-- The dihedral relation `(12) (123)^k (12)⁻¹ = (123)^{-k}`, in the form required by
    `SemidirectProduct.lift` (paper `ex:twist`). -/
theorem c3c2ToS3_compat (g : Multiplicative (ZMod 2)) :
    c3ToS3.comp (twistθC2 g).toMonoidHom
      = (MulAut.conj (c2ToS3 g)).toMonoidHom.comp c3ToS3 := by
  have key : ∀ (g : Multiplicative (ZMod 2)) (n : G3),
      c3ToS3 (twistθC2 g n) = c2ToS3 g * c3ToS3 n * (c2ToS3 g)⁻¹ := by decide
  exact MonoidHom.ext fun n => key g n

/-- `C₃ ⋊_θ C₂ →* S₃` (paper `ex:twist`). -/
def c3c2ToS3 : SemidirectProduct G3 (Multiplicative (ZMod 2)) twistθC2 →* Equiv.Perm (Fin 3) :=
  SemidirectProduct.lift c3ToS3 c2ToS3 c3c2ToS3_compat

/-- `c3c2ToS3` is bijective (paper `ex:twist`). -/
theorem c3c2ToS3_bijective : Function.Bijective c3c2ToS3 := by
  have hinj : ∀ (a c : G3) (b e : Multiplicative (ZMod 2)),
      c3ToS3 a * c2ToS3 b = c3ToS3 c * c2ToS3 e → a = c ∧ b = e := by decide
  have hsurj : ∀ σ : Equiv.Perm (Fin 3), ∃ a : G3, ∃ b : Multiplicative (ZMod 2),
      c3ToS3 a * c2ToS3 b = σ := by decide
  refine ⟨fun x y hxy => ?_, fun σ => ?_⟩
  · obtain ⟨h1, h2⟩ := hinj x.left y.left x.right y.right hxy
    exact SemidirectProduct.ext h1 h2
  · obtain ⟨a, b, h⟩ := hsurj σ
    exact ⟨⟨a, b⟩, h⟩

/-- Paper `ex:twist`: `C₃ ⋊_θ C₂ ≅ S₃`. -/
noncomputable def c3c2MulEquivS3 :
    SemidirectProduct G3 (Multiplicative (ZMod 2)) twistθC2 ≃* Equiv.Perm (Fin 3) :=
  MulEquiv.ofBijective c3c2ToS3 c3c2ToS3_bijective

/-- Paper `ex:twist`: `Sym_H^θ(p) ≅ C₃ ⋊ C₂ ≅ S₃`. -/
noncomputable def twistSymPerm :
    AutBoxGθOver twistData twistH twistθ ≃* Equiv.Perm (Fin 3) :=
  twistSym.trans c3c2MulEquivS3

/-- The generator `r` of `C₃ = G3` (paper `ex:twist`). -/
def twistR : G3 := Multiplicative.ofAdd 1

/-- The Core isomorphism of `thm:twisted` inverts the canonical map `G ⋊_θ H →* Sym_H^θ(p)`
    (helper for paper `ex:twist`). -/
theorem twistSemidirectH_apply_semidirectTo (x : SemidirectProduct G3 twistH twistθ) :
    twistSemidirectH (semidirectToAutBoxGθOver twistData twistH twistθ x) = x := by
  unfold twistSemidirectH autBoxGθOverMulEquivSemidirect
  exact MulEquiv.symm_apply_apply _ x

/-- Under `Sym_H^θ(p) ≅ S₃`, the fiber translation `Λ_g` goes to `(123)^g` (paper `ex:twist`). -/
theorem twistSymPerm_Λ (g : G3) :
    twistSymPerm (ΛHomθOver twistData twistH twistθ g) = c3ToS3 g := by
  have h1 : ΛHomθOver twistData twistH twistθ g
      = semidirectToAutBoxGθOver twistData twistH twistθ (SemidirectProduct.inl g) :=
    (semidirectToAutBoxGθOver_inl _ _ _ g).symm
  have h2 : twistSemidirectC2 (SemidirectProduct.inl g) = SemidirectProduct.inl g := by
    ext
    · rfl
    · show twistHMulEquiv 1 = 1
      exact map_one _
  rw [twistSymPerm, twistSym, MulEquiv.trans_apply, MulEquiv.trans_apply, h1,
    twistSemidirectH_apply_semidirectTo, h2]
  exact SemidirectProduct.lift_inl c3ToS3 c2ToS3 c3c2ToS3_compat g

/-- Under `Sym_H^θ(p) ≅ S₃`, `Λ_r` goes to the three-cycle `(123)` (paper `ex:twist`). -/
theorem twistSymPerm_Λ_r :
    twistSymPerm (ΛHomθOver twistData twistH twistθ twistR) = c[0, 1, 2] := by
  rw [twistSymPerm_Λ]
  decide

/-- Under `Sym_H^θ(p) ≅ S₃`, the canonical twisted lift `Ã_θ` of the interchange goes to the
    transposition `(12)` (paper `ex:twist`). -/
theorem twistSymPerm_lift :
    twistSymPerm (liftHomθOver twistData twistH twistθ twistHSwap) = Equiv.swap 0 1 := by
  have h1 : liftHomθOver twistData twistH twistθ twistHSwap
      = semidirectToAutBoxGθOver twistData twistH twistθ (SemidirectProduct.inr twistHSwap) :=
    (semidirectToAutBoxGθOver_inr _ _ _ twistHSwap).symm
  have h2 : twistSemidirectC2 (SemidirectProduct.inr twistHSwap) = SemidirectProduct.inr c2Gen := by
    ext
    · rfl
    · exact twistHMulEquiv_swap
  rw [twistSymPerm, twistSym, MulEquiv.trans_apply, MulEquiv.trans_apply, h1,
    twistSemidirectH_apply_semidirectTo, h2]
  exact (SemidirectProduct.lift_inr c3ToS3 c2ToS3 c3c2ToS3_compat c2Gen).trans
    (c2Hom_gen _ _ _ _ _ _)

/-- Paper `ex:twist` (instance of `thm:twisted`): on objects of `O = S × Pair(C₃)`, the canonical
    twisted lift `Ã_θ` of the interchange acts by `(s, g) ↦ (A s, θ_A(g)) = (A s, g⁻¹)`. -/
theorem twistLift_obj (s : Pair (Fin 2)) (g : G3) :
    (liftHomθOver twistData twistH twistθ twistHSwap).hom.obj (s, ⟨g⟩)
      = (swapAut.hom.obj s, ⟨g⁻¹⟩) := by
  show ((⟨Equiv.swap (0 : Fin 2) 1 s.pt⟩ : Pair (Fin 2)), (⟨1 * twistθ twistHSwap g⟩ : Pair G3))
    = _
  rw [twistθ_swap_apply, one_mul]
  rfl

/-! ## The conjugation formula `Ã_θ Λ_r Ã_θ⁻¹ = Λ_{r⁻¹}` -/

/-- Paper `ex:twist` (instance of `thm:twisted`): conjugating a fiber translation by the canonical
    twisted lift `Ã_θ` of the interchange inverts it, `Ã_θ Λ_g Ã_θ⁻¹ = Λ_{g⁻¹}` for all `g ∈ C₃`
    (group product in operator order). -/
theorem twist_conj (g : G3) :
    liftHomθOver twistData twistH twistθ twistHSwap * ΛHomθOver twistData twistH twistθ g
        * (liftHomθOver twistData twistH twistθ twistHSwap)⁻¹
      = ΛHomθOver twistData twistH twistθ g⁻¹ := by
  have h := DFunLike.congr_fun (liftHomθOver_conj twistData twistH twistθ twistHSwap) g
  simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, MulAut.conj_apply,
    twistθ_swap_apply] at h
  exact h.symm

/-- Paper `ex:twist`: `Ã_θ Λ_r Ã_θ⁻¹ = Λ_{r⁻¹}` for the generator `r` of `C₃`. -/
theorem twist_conj_r :
    liftHomθOver twistData twistH twistθ twistHSwap * ΛHomθOver twistData twistH twistθ twistR
        * (liftHomθOver twistData twistH twistθ twistHSwap)⁻¹
      = ΛHomθOver twistData twistH twistθ twistR⁻¹ :=
  twist_conj twistR

/-! ## Left versus right translation in `S₃` -/

/-- Paper `ex:twist`: with right-to-left composition, `(12)(23) = (123)`; on `Fin 3`,
    `swap 0 1 * swap 1 2 = c[0, 1, 2]` (`0 ↦ 1 ↦ 2 ↦ 0`). -/
theorem s3_swap01_mul_swap12 : Equiv.swap (0 : Fin 3) 1 * Equiv.swap 1 2 = c[0, 1, 2] := by
  decide

/-- Paper `ex:twist`: `(23)(12) = (132)`; on `Fin 3`, `swap 1 2 * swap 0 1 = c[0, 2, 1]`
    (`0 ↦ 2 ↦ 1 ↦ 0`). -/
theorem s3_swap12_mul_swap01 : Equiv.swap (1 : Fin 3) 2 * Equiv.swap 0 1 = c[0, 2, 1] := by
  decide

/-- Explicit values of `(12)(23)`: `0 ↦ 1`, `1 ↦ 2`, `2 ↦ 0` (paper `ex:twist`). -/
theorem s3_swap01_mul_swap12_apply :
    (Equiv.swap (0 : Fin 3) 1 * Equiv.swap 1 2 : Equiv.Perm (Fin 3)) 0 = 1 ∧
    (Equiv.swap (0 : Fin 3) 1 * Equiv.swap 1 2 : Equiv.Perm (Fin 3)) 1 = 2 ∧
    (Equiv.swap (0 : Fin 3) 1 * Equiv.swap 1 2 : Equiv.Perm (Fin 3)) 2 = 0 := by
  decide

/-- Explicit values of `(23)(12)`: `0 ↦ 2`, `1 ↦ 0`, `2 ↦ 1` (paper `ex:twist`). -/
theorem s3_swap12_mul_swap01_apply :
    (Equiv.swap (1 : Fin 3) 2 * Equiv.swap 0 1 : Equiv.Perm (Fin 3)) 0 = 2 ∧
    (Equiv.swap (1 : Fin 3) 2 * Equiv.swap 0 1 : Equiv.Perm (Fin 3)) 1 = 0 ∧
    (Equiv.swap (1 : Fin 3) 2 * Equiv.swap 0 1 : Equiv.Perm (Fin 3)) 2 = 1 := by
  decide

/-- The two three-cycles are distinct: `(123) ≠ (132)` (paper `ex:twist`). -/
theorem s3_left_ne_right :
    Equiv.swap (0 : Fin 3) 1 * Equiv.swap 1 2 ≠ Equiv.swap (1 : Fin 3) 2 * Equiv.swap 0 1 := by
  decide

/-- Paper `ex:twist`: for `G = S₃` (presentation `witness S₃`), `a = (12)` and the object with
    coordinate `g = (23)`, the normalized translation `Λ_a` produces coordinate `a g = (123)`. -/
theorem s3_Λ_obj :
    (Λ (witness (Equiv.Perm (Fin 3))) (Equiv.swap 0 1)).obj ⟨Equiv.swap 1 2⟩ = ⟨c[0, 1, 2]⟩ := by
  show (⟨1 * (Equiv.swap 0 1 * Equiv.swap 1 2)⟩ : Pair (Equiv.Perm (Fin 3))) = _
  rw [one_mul, s3_swap01_mul_swap12]

/-- Paper `ex:twist`: for the same data, the right action `R_a` produces coordinate
    `g a = (132)`. -/
theorem s3_actFunctor_obj :
    ((witness (Equiv.Perm (Fin 3))).actFunctor (Equiv.swap 0 1)).obj ⟨Equiv.swap 1 2⟩
      = ⟨c[0, 2, 1]⟩ := by
  show (⟨Equiv.swap 1 2 * Equiv.swap 0 1⟩ : Pair (Equiv.Perm (Fin 3))) = _
  rw [s3_swap12_mul_swap01]

/-- Paper `ex:twist`: `Λ_a` and `R_a` must not be identified for a general (non-abelian) `G`:
    for `G = S₃` and `a = (12)`, `Λ_a ≠ R_a` (witnessed at the object with coordinate `(23)`). -/
theorem s3_Λ_ne_actFunctor :
    Λ (witness (Equiv.Perm (Fin 3))) (Equiv.swap 0 1)
      ≠ (witness (Equiv.Perm (Fin 3))).actFunctor (Equiv.swap 0 1) := by
  intro h
  have h' := congrArg (fun F => F.obj (⟨Equiv.swap 1 2⟩ : Pair (Equiv.Perm (Fin 3)))) h
  simp only [s3_Λ_obj, s3_actFunctor_obj] at h'
  exact absurd (congrArg Pair.pt h') (by decide)
